### PR TITLE
Add az-cli to support azure

### PR DESCRIPTION
**Pull request by assapir**
This is closing #15. Might need to update docs about how to use service principal password as env var so it would work

### CODE REVIEW

**Comment by assapir** [comment]
In order to use the Service Principal you still need the az cli to be in the image. Maybe its in a different flavor of the terraform image?

**Comment by im2nguyen** [comment]
Hrm, that's interesting... based on the docs, it seems like you don't need the CLI.

First, create your service principal.

```
$ az ad sp create-for-rbac --role="Contributor" 
{
  "appId": "00000000-0000-0000-0000-000000000000",
  "displayName": "azure-cli-2017-06-05-10-41-15",
  "name": "http://azure-cli-2017-06-05-10-41-15",
  "password": "0000-0000-0000-0000-000000000000",
  "tenant": "00000000-0000-0000-0000-000000000000"
}
```

Then, [configure Terraform to use the service principal](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret#configuring-the-service-principal-in-terraform) by setting the following environment variables only (no CLI).

```
$ export ARM_CLIENT_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_CLIENT_SECRET="00000000-0000-0000-0000-000000000000"
$ export ARM_SUBSCRIPTION_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_TENANT_ID="00000000-0000-0000-0000-000000000000"
```

The provider block will automatically use these to auth to Azure.

```
# Configure the Microsoft Azure Provider
provider "azurerm" {
  features {}
}
```

**Comment by assapir** [comment]
Mmm, I will try that. If it will work without it, I will close this pr. Thanks!

**Comment by assapir** [comment]
confirming that it is working with SP. closing. sorry and thanks for the patient on me :)

**Pull request closed without merging**
